---
- name: Crear VM en VMware
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: "{{ vm_state }}"
    guest_id: "{{ vm_guestid }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
    disk:
      - size_gb: "{{ vm_disk_gb }}"
        type: thin
        datastore: "{{ vcenter_datastore }}"
    networks:
      - name: "{{ vcenter_network }}"
        type: vmxnet3
    wait_for_ip_address: no
  delegate_to: localhost
